package domain

import (
	"errors"
	"time"
)

// Severity describes the risk level of an alert.
type Severity string

const (
	SeverityLow      Severity = "low"
	SeverityMedium   Severity = "medium"
	SeverityHigh     Severity = "high"
	SeverityCritical Severity = "critical"
)

// Rank orders severities from low (1) to critical (4). Unknown severities rank 0.
func (s Severity) Rank() int {
	switch s {
	case SeverityLow:
		return 1
	case SeverityMedium:
		return 2
	case SeverityHigh:
		return 3
	case SeverityCritical:
		return 4
	default:
		return 0
	}
}

// Valid reports whether s is one of the known severities.
func (s Severity) Valid() bool { return s.Rank() > 0 }

// Alert is generated by the detection engine when a rule fires.
// Timestamp is the time of the event that triggered the alert.
type Alert struct {
	ID           string      `json:"id"`
	Timestamp    time.Time   `json:"timestamp"`
	IP           string      `json:"ip"`
	EventType    EventType   `json:"event_type"`
	Severity     Severity    `json:"severity"`
	Reason       string      `json:"reason"`
	AIAnalysis   *AIAnalysis `json:"ai_analysis,omitempty"`
	EventCount   int         `json:"event_count"`
	TriggerRule  string      `json:"trigger_rule"`
	RelatedRules []string    `json:"related_rules,omitempty"`
}

// AI analysis states.
const (
	AIStatusPending   = "pending"   // queued, result not yet available
	AIStatusCompleted = "completed" // verdict and summary are set
	AIStatusFailed    = "failed"    // provider error or unusable answer, see Error
	AIStatusRefused   = "refused"   // the model declined to analyze the content
	AIStatusSkipped   = "skipped"   // not analyzed, e.g. because the queue was full
)

// AIAnalysis is an AI model's assessment of an alert. It only adds context for
// an analyst and never changes the alert's severity: the analyzed event data
// may be written by an attacker trying to talk the model into "benign".
type AIAnalysis struct {
	Status            string     `json:"status"`
	Verdict           string     `json:"verdict,omitempty"`    // malicious, suspicious, benign, unknown
	Confidence        string     `json:"confidence,omitempty"` // low, medium, high
	Category          string     `json:"category,omitempty"`
	Summary           string     `json:"summary,omitempty"`
	RecommendedAction string     `json:"recommended_action,omitempty"`
	Provider          string     `json:"provider,omitempty"`
	Model             string     `json:"model,omitempty"`
	Error             string     `json:"error,omitempty"`
	AnalyzedAt        *time.Time `json:"analyzed_at,omitempty"`
}

// ErrAIRefused marks an analysis the model declined to perform. Safety filters
// may react to real attack payloads (SQL injection, exploit strings) in events.
var ErrAIRefused = errors.New("the model declined to analyze the content")
